using Microsoft.CodeAnalysis;

namespace Monry.Toolbox.Generator;

[Generator(LanguageNames.CSharp)]
public class CommandPublishableIncrementalSourceGenerator : IIncrementalGenerator
{
    private const string Namespace = "Monry.Toolbox.Attributes";
    private const string AttributeName = "CommandPublishableAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var source = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                $"{Namespace}.{AttributeName}",
                // 絞り込みは属性だけで OK
                (_, _) => true,
                (syntaxContext, _) => syntaxContext
            );
        context.RegisterSourceOutput(source, Emit);
    }

    private static void Emit(SourceProductionContext context, GeneratorAttributeSyntaxContext syntaxContext)
    {
        var typeSymbol = (INamedTypeSymbol)syntaxContext.TargetSymbol;
        var isGlobalNamespace = typeSymbol.ContainingNamespace.IsGlobalNamespace;
        var @namespace = isGlobalNamespace
            ? string.Empty
            : $"namespace {typeSymbol.ContainingNamespace.ToDisplayString()}";
        var fullTypeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", "")
            .Replace("<", "_")
            .Replace(">", "_");
        var indent = isGlobalNamespace ? string.Empty : "    ";

        var code = $$"""
            // <auto-generated />
            using Monry.Toolbox.VitalRouter;
            using VContainer;
            using VitalRouter;

            {{@namespace}}
            {{(isGlobalNamespace ? string.Empty : "{")}}
            {{indent}}partial class {{typeSymbol.Name}} : ICommandPublishable
            {{indent}}{
            {{indent}}    [Inject] public ICommandPublisher CommandPublisher { get; set; } = default!;
            {{indent}}}
            {{(isGlobalNamespace ? string.Empty : "}")}}
            """;
        context.AddSource($"{fullTypeName}.CommandPublishable.g.cs", code);
    }
}
